### ISSUE TITLE
[Feature request]: Bate-n lemn

### ISSUE THREAD

**Issue by meutzitzu** [tincaMatei/trapperu_real#1]
Everytime it says something which can have disastrous consequences such as "Arghezi, Caragiale, Barbu" etc there should be a custom command for it to follow-up with a `🤜🪵` expression

**Comment by tincaMatei** [comment]
You can do this via the `/adauga` command. Also jokes on you, I already did that on some groups :)

To do exactly what you asked for, you should either do:

* On the group chat: `/adauga arghezi|caragiale|barbu~🤜🪵`
* On the group chat: `/alias [alias]`, and then privately with the bot (so other people from the group chat won't know what command you added, so when the bot starts talking, it will come as a surprise) you should send `/adauga [alias]~arghezi|caragiale|barbu~🤜🪵`, where `[alias]` is any name that you want

For instance, I did `/adauga moara|slavici|(ultima&noapte)|(camil&petrescu)|harap|creanga|enigma|otiliei|calinescu|ion|rebreanu|baltagul|sadoveanu|eminescu|luceafarul|barbu|bacovia|plumb|arghezi|(flori&de&(mucegai|mucigai))|blaga|corola|bac~aoleo dai bacu regrete eterne boss` to answer with "aoleo dai bacu regrete eterne boss" whenever someone mentions the author or his work (although I think I forgot Caragiale).
